
DROP TABLE IF EXISTS targets;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS calendar_user;
DROP TABLE IF EXISTS calendars;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS nations;
