START TRANSACTION;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS personal_access_tokens;
DROP TABLE IF EXISTS nations;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS calendars;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS targets;
DROP TABLE IF EXISTS calendar_user;
DROP TABLE IF EXISTS migrations;

SET FOREIGN_KEY_CHECKS = 1;
COMMIT;